### ISSUE TITLE
How can a contract in casper hold funds and how to manipulate them

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/docs#217] opened 2022-02-03 18:43 UTC
@piotr-dziubecki commented on [Mon Oct 25 2021](https://github.com/casper-network/Governance/issues/85)

We have an example contract demonstrating this functionality but that's currently in the private repo as it was using slightly outdated contract APIs. We have work already assigned to make this code public as soon as possible as this is frequently asked

---

@piotr-dziubecki commented on [Mon Oct 25 2021](https://github.com/casper-network/Governance/issues/85#issuecomment-950907579)

https://github.com/casper-ecosystem/payment-example/pull/3

**Comment by piotr-dziubecki** [comment] 2022-02-03 18:44
we need to review the examples for this

**Comment by devendran-m** [comment] 2022-03-30 14:10
Duplicate of #286. hence closing this ticket.

**Closed by devendran-m** 2022-03-30 14:10 UTC
Labels: documentation
